INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('ATMEGA 2560', '2', '2', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('All in 1 Super Multi Adapter', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Viedeo Spectacles Control Kit', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('ClabSys 2410', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('FALINUX (EZ-X5)', '2', '2', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('ALTERA FLEX (MAX)', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('CPU cooler', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('로지텍 웹캠 프로 9000', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('CCD VIDEO CAMERA', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('DIRECT VOX PROAUDIO ( PHW-22 )', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('IKVA 다운용 TRANSFORMER', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('X DRIVE-6', '3', '3', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('ALTERA DE2', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('SWALLOW advance 충전기', '1', '1', NULL);
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Galaxy Note 8.0', '1', '0', '8W6M');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Galaxy Note2', '1', '1', 'OHRA');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Galaxy S4', '1', '1', 'OB3J');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Leap Motion', '1', '1', '8302');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Leap Motion', '1', '1', '8737');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Nexus 7', '1', '1', '5307');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Nexus 7', '1', '1', '5032');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('WIRELESS Web Camera', '1', '1', 'WCM-04_1');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Tizen Reference Phone', '1', '1', 'RF1D40SEYEV');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Tizen Reference Phone', '1', '1', 'RF1D41RSF9J');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Gear2', '1', '1', 'LBVT');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Gear2', '1', '1', 'CP7E');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Gear2', '1', '1', 'CMEL');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Gear2', '1', '1', 'A80H');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Gear2', '1', '1', '9Q3D');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Chromecast', '1', '1', '2B07101W93CS');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('로지텍 웹캠 C210', '1', '1', '1');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Galaxy S4', '1', '1', '0AZD');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Tizen Z1', '1', '1', '754K');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Tizen Z1', '1', '1', '75AM');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Kinect(Window용)', '1', '1', '3567721642');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Kinect(Window용)', '1', '1', '3491421642');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Kinect(XBOX용)', '1', '1', '74363510835');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Leap Motion', '1', '1', '6836');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('Leap Motion', '1', '1', '3263');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('로지텍 웹캠 C210', '1', '1', '2');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('로지텍 웹캠 프로 c920', '1', '1', '1401LZ0571T9');
INSERT INTO `swmem`.`t_hardware` (`h_name`, `h_total`, `h_remaining`, `h_serial`) VALUES ('로지텍 웹캠 프로 c920', '1', '1', '1333LZ04AGT9');
